# Generated by Django 4.1 on 2022-12-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="user",
        ),
    ]
