# Generated by Django 4.1 on 2022-12-12 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dompet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saldo", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArusKas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nominal", models.IntegerField()),
                ("keterangan", models.CharField(max_length=255)),
                ("tipe", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dompet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dompet.dompet"
                    ),
                ),
            ],
        ),
    ]
