# Generated by Django 4.1 on 2022-10-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dompet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aruskas",
            name="tipe",
            field=models.IntegerField(),
        ),
    ]
