# Generated by Django 4.1 on 2022-12-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dompet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aruskas",
            name="dompet",
        ),
        migrations.RemoveField(
            model_name="dompet",
            name="user",
        ),
    ]
