# Generated by Django 4.1 on 2022-12-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dompet", "0003_alter_dompet_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aruskas",
            name="dompet",
        ),
        migrations.RemoveField(
            model_name="dompet",
            name="user",
        ),
    ]
