# Generated by Django 4.1 on 2022-10-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forum_komenpertama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='komenPertama',
            field=models.TextField(default='Belum ada komentar'),
        ),
    ]
