# Generated by Django 4.1 on 2022-12-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("berita", "0002_berita_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="berita",
            name="user",
        ),
    ]
