# Generated by Django 4.1 on 2022-10-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kurs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="currency",
            old_name="currency",
            new_name="name",
        ),
        migrations.AddField(
            model_name="currency",
            name="code",
            field=models.CharField(default=232, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="currency",
            name="icon",
            field=models.FilePathField(max_length=200),
        ),
    ]
