# Generated by Django 4.1 on 2022-10-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kurs", "0002_rename_currency_currency_name_currency_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="amount",
            field=models.DecimalField(decimal_places=6, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name="currency",
            name="change_1d",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="currency",
            name="change_1m",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="currency",
            name="change_1w",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="currency",
            name="change_1y",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="currency",
            name="last_updated",
            field=models.DateTimeField(null=True),
        ),
    ]
