# Generated by Django 4.1 on 2022-10-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kurs", "0003_currency_amount_currency_change_1d_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="last_updated",
            field=models.DateField(null=True),
        ),
    ]
