# Generated by Django 4.1 on 2022-10-27 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kurs", "0004_alter_currency_last_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currency",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="currency",
            name="change_1d",
        ),
        migrations.RemoveField(
            model_name="currency",
            name="change_1m",
        ),
        migrations.RemoveField(
            model_name="currency",
            name="change_1w",
        ),
        migrations.RemoveField(
            model_name="currency",
            name="change_1y",
        ),
        migrations.RemoveField(
            model_name="currency",
            name="last_updated",
        ),
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=6, max_digits=1000, null=True),
                ),
                (
                    "change_1d",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "change_1w",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "change_1m",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "change_1y",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("change_1d_color", models.CharField(max_length=10, null=True)),
                ("change_1w_color", models.CharField(max_length=10, null=True)),
                ("change_1m_color", models.CharField(max_length=10, null=True)),
                ("change_1y_color", models.CharField(max_length=10, null=True)),
                ("last_updated", models.DateField(null=True)),
                (
                    "source_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_currency",
                        to="kurs.currency",
                    ),
                ),
                (
                    "target_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_currency",
                        to="kurs.currency",
                    ),
                ),
            ],
        ),
    ]
